apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  annotations: 
    configmanagement.gke.io/namespace-selector: europe-selector
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
